### ISSUE TITLE
docs: update README

### ISSUE THREAD

**Issue by RamGoel** [RamGoel/easyCDN#8]
This issue focuses on creating a proper README.md file for this project. At this point I think it is a better option to include the contents of `contributing.md` into `readme.md` so that developers can access the contents easily.

**Comment by JoshLamptey** [comment]
Hi Ram I will get this done in an hour

**Comment by RamGoel** [comment]
okay, works.

**Comment by JoshLamptey** [comment]
hii yeah i am done. But I am struggling with making a pr (i haven't done this a lot of times ;) )

**Comment by JoshLamptey** [comment]
okay i did it i am waiting for your review

**Comment by RamGoel** [comment]
> okay i did it i am waiting for your review

You haven't created a PR yet.

**Comment by RamGoel** [comment]
fixed in #12
